vim.env.i = vim.env.myvimrc -- Init.lua
vim.env.n = regex.gsub"//""\\"(vim.fs.dirname(vim.env.i)) -- Init.lua
vim.env.c = vim.env.xdg_config_home -- Config
vim.env.w = vim.env.works -- Works
vim.env.f = vim.env.forks -- Forks
vim.env.s = vim.env.appdata .. '/CorvusSKK' -- corvusSkk
vim.env.d = vim.env.works .. "/dictionaries.skk" -- skk-Dictionary
vim.env.l = vim.env.works .. "/modules.nvim/lua" -- Lua-modules
vim.env.t = vim.env.home .. "/test" -- Test
vim.env.m = vim.env.home .. "/memos" -- Memos
